- name: Instalar aplicação WEB no servidor EC2 AWS
  hosts: grailsservers
  tasks:
    - name: Instalar docker e docker-compose
      become: yes
      shell:
        cmd: |
          sudo apt-get -yq install \
              ca-certificates \
              curl \
              gnupg \
              lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
          echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get -yq install docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose

    - name: Copiar docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: ~/

    - name: Executar docker-compose.yml
      shell:
        cmd: sudo docker-compose up -d
      register: output

    - name: Output
      debug:
        var: output
        